language: cpp

git:
  depth: false

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    env: TASK=cpp_test OS=ubuntu
  - os: linux
    sudo: required
    services: docker
    env: TASK=cpp_test OS=centos
  - os: linux
    sudo: required
    services: docker
    env: TASK=python2_test OS=ubuntu
  - os: linux
    sudo: required
    services: docker
    env: TASK=python3_test OS=ubuntu
  - os: osx
    env: TASK=cpp_test

before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker build -t test_ngraph -f .ci/travis/$OS/Dockerfile .
  fi
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update && brew install llvm@3.9 automake
  fi

install: true

script:
- .ci/travis/run_test.sh

branches:
  only:
  - "master"
