sudo: required

language: cpp

services:
  - docker

env:
  - TASK=cpp_test OS=ubuntu
  - TASK=cpp_test OS=centos
  - TASK=python2_test OS=ubuntu
  - TASK=python3_test OS=ubuntu

before_install:
  - docker build -t test_ngraph -f .ci/travis/$OS/Dockerfile .

install: true

script:
  - .ci/travis/run_test.sh

branches:
  only:
    - "master"
