language: cpp

git:
  depth: false

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    env: TASK=cpp_test OS=ubuntu
  - os: linux
    sudo: required
    services: docker
    env: TASK=cpp_test OS=centos
  - os: osx
    env: TASK=cpp_test
  - os: linux
    sudo: required
    services: docker
    env: TASK=python2_test OS=ubuntu
  - os: linux
    sudo: required
    services: docker
    env: TASK=python3_test OS=ubuntu

before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker build -t test_ngraph -f .ci/travis/$OS/Dockerfile .
  fi

install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir $TRAVIS_BUILD_DIR/build
    cd $TRAVIS_BUILD_DIR/build
    cmake .. -DNGRAPH_CPU_ENABLE=FALSE \
             -DNGRAPH_USE_PREBUILT_LLVM=TRUE \
             -DNGRAPH_ONNX_IMPORT_ENABLE=TRUE \
             -DCMAKE_INSTALL_PREFIX="~/ngraph_dist"
    make -j 2
  fi

script:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    cd $TRAVIS_BUILD_DIR/build
    make unit-test-check
  fi
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    .ci/travis/run_test.sh
  fi

branches:
  only:
  - "master"
