sudo: required

language: cpp

services:
  - docker

git:
  depth: false

env:
  - travis_wait 15 TASK=cpp_test
  - travis_wait 15 TASK=python2_test
  - travis_wait 15 TASK=python3_test

before_install:
  - docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile .

install: true

script:
  - .ci/travis/ubuntu/run_test.sh

branches:
  only:
    - "master"
