sudo: required

language: cpp

services:
  - docker

git:
  depth: false

env:
  - TASK=cpp_test OS=ubuntu
  - TASK=cpp_test OS=centos
  - TASK=python2_test OS=ubuntu
  - TASK=python3_test OS=ubuntu

before_install:
  - |
    if [ "TASK" == "cpp_test" ]; then
      docker build -t test_ngraph -f .ci/travis/$OS/Dockerfile .
    else
      docker build -t test_ngraph -f .ci/travis/$OS/Dockerfile --build-arg buildtype=interpreter .
    fi

install: true

script:
  - .ci/travis/run_test.sh

branches:
  only:
    - "master"
