sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile .

install: true

script:
  - docker run test_ngraph

branches:
  only:
    - "master"
