sudo: required

language: cpp

services:
  - docker

git:
  depth: false

env:
  - TASK=cpp_test


before_install:
  - docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile .

install: true

script:
  - .ci/travis/ubuntu/run_test.sh

branches:
  only:
    - "master"
