sudo: required

language: cpp

services:
  - docker

git:
  depth: false

env:
  - TASK=cpp_test
  - TASK=python2_test
  - TASK=python3_test

before_install:
  - |
    if [ "TASK" == "cpp_test" ]; then 
      docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile .
    else
      docker build -t test_ngraph -f .ci/travis/ubuntu/Dockerfile --build-arg buildtype=interpreter .
    fi

install: true

script:
  - .ci/travis/ubuntu/run_test.sh

branches:
  only:
    - "master"
