ngraph::Node
friend class autodiff::Adjoints
friend class descriptor::Input
void replace_node_users_arguments(std::shared_ptr< Node > target, std::shared_ptr< Node > replacement)
std::ostream& operator<<(std::ostream &, const Node &)
std::unordered_set<descriptor::Tensor*> ngraph::Node::liveness_live_list
std::unordered_set<descriptor::Tensor*> ngraph::Node::liveness_new_list
std::unordered_set<descriptor::Tensor*> ngraph::Node::liveness_free_list
std::string ngraph::Node::m_node_type
std::multiset<Node*> ngraph::Node::m_users
std::string ngraph::Node::m_name
size_t ngraph::Node::m_instance_id
std::deque<descriptor::Input> ngraph::Node::m_inputs
std::deque<descriptor::Output> ngraph::Node::m_outputs
bool ngraph::Node::m_is_output
std::unordered_map<Node*, autodiff::Adjoints> ngraph::Node::m_adjoint_map
atomic< size_t > Node::m_next_instance_id
Nodes ngraph::Node::m_arguments
Node::Node(const std::string &node_type, const Nodes &arguments)
virtual ngraph::Node::~Node()
virtual void ngraph::Node::generate_adjoints(autodiff::Adjoints &adjoints, const std::shared_ptr< Node > &delta)
void Node::add_output(const element::Type &element_type, const Shape &shape)
std::string ngraph::Node::description() const
The class name, must not contain spaces.
std::string Node::get_name() const
void Node::set_name(const std::string &name)
void ngraph::Node::clear_arguments()
const std::multiset<Node*>& ngraph::Node::users() const
std::string Node::get_node_id() const
bool ngraph::Node::is_same_op_type(const std::shared_ptr< Node > &node) const
Return true if this has the same implementing class as node. This will be used by the pattern matcher when comparing a pattern graph against the graph.
void ngraph::Node::set_value_type_checked(const std::shared_ptr< const TensorViewType > &value_type)
void Node::set_value_type_checked(const element::Type &element_type, const Shape &shape)
bool Node::is_parameter() const
bool Node::is_output() const
void Node::set_is_output()
bool Node::is_constant() const
virtual bool ngraph::Node::is_commutative()
size_t ngraph::Node::get_instance_id() const
std::deque<descriptor::Input>& ngraph::Node::get_inputs()
const std::deque<descriptor::Input>& ngraph::Node::get_inputs() const
std::deque< descriptor::Output > & Node::get_outputs()
const std::deque< descriptor::Output > & Node::get_outputs() const
size_t Node::get_output_size() const
Returns the number of outputs on the for the node.
const element::Type & Node::get_output_element_type(size_t i) const
Returns the element type for output i.
const element::Type & Node::get_element_type() const
Checks that there is exactly one output and returns its element type.
const Shape & Node::get_output_shape(size_t i) const
Returns the shape for output i.
const Shape & Node::get_shape() const
Checks that there is exactly one output and returns its shape.
descriptor::Tensor & Node::get_output_tensor(size_t i) const
Returns the tensor for output i.
descriptor::Tensor & Node::get_output_tensor() const
Checks that there is exactly one output and returns its tensor.
shared_ptr< descriptor::TensorView > Node::get_output_tensor_view(size_t i) const
Returns the tensor view of output i.
shared_ptr< descriptor::TensorView > Node::get_output_tensor_view() const
Checks that there is exactly one output and returns its tensor view.
const std::set< descriptor::Input * > & Node::get_output_inputs(size_t i) const
Returns the set of inputs using output i.
size_t Node::get_input_size() const
Returns the number of inputs for the op.
Referenced by ngraph::op::FunctionCall::FunctionCall.
const element::Type & Node::get_input_element_type(size_t i) const
Returns the element type of input i.
Referenced by ngraph::op::FunctionCall::FunctionCall.
const Shape & Node::get_input_shape(size_t i) const
Returns the shape of input i.
Referenced by ngraph::op::FunctionCall::FunctionCall.
std::shared_ptr< Node > Node::backprop_node(const std::shared_ptr< Node > &x, const std::shared_ptr< Node > &c)
Nodes Node::get_input_ops()
std::shared_ptr< Node > Node::get_input_op(size_t index)
virtual std::shared_ptr<Node> ngraph::Node::copy_with_new_args(const std::vector< std::shared_ptr< Node >> &new_args) const =0
std::vector< std::shared_ptr< Function > > Node::get_functions() const
bool Node::has_same_type(std::shared_ptr< const Node > node) const
Nodes& ngraph::Node::get_arguments_FOR_GRAPH_REWRITE_ONLY()