ngraph::op::Constant
element::Type ngraph::op::Constant::m_element_type
Shape ngraph::op::Constant::m_shape
void* ngraph::op::Constant::m_data
ngraph::op::Constant::Constant(const element::Type &type, Shape shape, const std::vector< T > &values)
Constructs a tensor constant.
type The element type of the tensor constant. shape The shape of the tensor constant. values A vector of literals for initializing the tensor constant. The size of values must match the size of the shape.
ngraph::op::Constant::Constant(const element::Type &type, Shape shape, const std::vector< std::string > &values)
Constructs a tensor constant This constructor is mainly to support deserialization of constants.
type The element type of the tensor constant. shape The shape of the tensor constant. values A list of string values to use as the constant data.
ngraph::op::Constant::Constant(const element::Type &type, const Shape &shape, const void *data)
Constructs a tensor constant with the same initialization value copied across the tensor. This constructor is mainly to support deserialization of constants.
type The element type of the tensor constant. shape The shape of the tensor constant. data A void* to constant data.
op::Constant::~Constant()
virtual std::shared_ptr<Node> ngraph::op::Constant::copy_with_new_args(const std::vector< std::shared_ptr< Node >> &new_args) const override
std::vector< std::string > op::Constant::get_value_strings() const
The initialization literals for the tensor constant.
std::vector<T> ngraph::op::Constant::get_vector() const
const void* ngraph::op::Constant::get_data_ptr() const
bool ngraph::op::Constant::is_constant() const override
static std::shared_ptr<op::Constant> ngraph::op::Constant::create(const element::Type &type, Shape shape, const std::vector< T > values)
Wrapper around constructing a shared_ptr of a Constant.
type The element type of the tensor constant. shape The shape of the tensor constant. values A vector of values to use as the constant data.
Referenced by ngraph::builder::l2_norm, ngraph::builder::mean, ngraph::builder::std_dev, ngraph::builder::variance.
static std::shared_ptr<op::Constant> ngraph::op::Constant::create(const element::Type &type, Shape shape, std::initializer_list< T > values)
Wrapper around constructing a shared_ptr of a Constant.
type The element type of the tensor constant. shape The shape of the tensor constant. values An initializer_list of values to use as the constant data.
void ngraph::op::Constant::write_values(const std::vector< T > &values)
void ngraph::op::Constant::write_buffer(void *target, const std::vector< U > &source, size_t count)
void ngraph::op::Constant::write_to_buffer(const element::Type &target_type, const Shape &target_shape, const std::vector< T > &source, void *target, size_t target_element_count)