ngraph::builder
static Autobroadcast_plan ngraph::builder::compute_shapes_and_broadcast_axes(const ngraph::Shape &arg1_in_shape, const ngraph::Shape &arg2_in_shape)
Compute the details regarding what reshape and/or broadcast operations must be applied to arg1 and/or arg2, as well as what the final resulting shape shall be.
If this algorithm cannot handle the particular combination of shapes supplied as inputs, throw an ngraph::builder::autobroadcast_incompatible_shapes exception. ngraph::builder::autobroadcast_incompatible_shapes
static std::shared_ptr<Node> ngraph::builder::add_required_ops(const std::shared_ptr< Node > &node, const ngraph::Shape &node_shape_after_possible_reshaping, const ngraph::AxisSet &node_broadcast_axes, const ngraph::Shape &node_final_shape)
If necessary, wrap node with an additional reshape and/or broadcast op. Return a pointer to the node that produces the wrapped value. If no additional reshape or broadcast op was needed, simply return node.
std::pair< std::shared_ptr< Node >, std::shared_ptr< Node > > ngraph::builder::numpy_broadcast(const std::pair< std::shared_ptr< Node >, std::shared_ptr< Node >> &args)
Wrap two graph nodes, if necessary, to obtain values with identical shapes, using NumPy's auto-broadcast rules.
The elements in the std::pair returned by this function correspond to those supplied in the std::pair provided via args.If args.first and args.second produce identical shapes, then the returned std::pair will have the same value as args.If args.first and args.second produce different shapes, then this function creates new ngraph::op::Reshape and/or ngraph::op::Broadcast nodes, as needed, to wrap args.first and/or args.second in a manner that yields values with the same shape.There are some shape combinations which the autobroadcast algoritm cannot handle. An exception is thrown when such combinations are provided to this function. args.first is not nullargs.second is not null The ngraph::Node objects pointed to by args.first and args.second have not been altered by this function, except by possibly having added consumers of their values.If an exception was not thrown, then the return value's first and second elements point to ngraph::Node objects whose output values have the same shape. ngraph::builder::autobroadcast_incompatible_shapes
References numpy_broadcast.
Referenced by numpy_broadcast, make_with_numpy_broadcast.
std::shared_ptr<NodeType> ngraph::builder::make_with_numpy_broadcast(const std::shared_ptr< Node > &operand1_reshapeable, const std::shared_ptr< Node > &operand2_reshapeable)
Create a new NodeType node, and any additional nodes required to simulate NumPy-style autobroadcast semantics. Intended for binary operations such as "Add". operand1_reshapeable The first operand to supply to the NodeType constructor. Subject to being wrapped with additional nodes required for autobroadcasting. Must not be null. operand2_reshapeable The second operand to supply to the NodeType constructor. Subject to being wrapped with additional nodes required for autobroadcasting. Must not be null. The sink node of any/all nodes created by this function. Will never be null. ngraph::builder::autobroadcast_incompatible_shapes
References numpy_broadcast.
std::shared_ptr<NodeType> ngraph::builder::make_with_numpy_broadcast(const std::shared_ptr< Node > &operand1, const std::shared_ptr< Node > &operand2_reshapeable, const std::shared_ptr< Node > &operand3_reshapeable)
Create a new NodeType node, and any additional nodes required to simulate NumPy-style autobroadcast semantics. Intended for non-binary operations such as "Select", where precisely the second and third operands are subject to autobroadcast semantics. operand1 This operand is not subject to autobraodcast logic, and will be passed as-is as the first argument to the NodeType constructor. operand2_reshapeable The second operand to supply to the NodeType constructor. Subject to being wrapped with additional nodes required for autobroadcasting. Must not be null. operand3_reshapeable The third operand to supply to the NodeType constructor. Subject to being wrapped with additional nodes required for autobroadcasting. Must not be null. The sink node of any/all nodes created by this function. Will never be null. ngraph::builder::autobroadcast_incompatible_shapes
References numpy_broadcast.
std::shared_ptr< Node > ngraph::builder::numpy_transpose(const std::shared_ptr< Node > &node, AxisVector order={})
Implement's Numpy's multidimensional transpose op. Doubles as DimShuffle.
If order is empty, the vector is transposed by reversing it's axes, i.e.shape [1,2,4] becomes shape [4,2,1]If order is provided, it should be a vector of unique axis positions ranging from 0 to N-1, when N is the length of the input shape. In this case, numpy_transpose acts like dimshuffle, soshape [1,2,4] with order [1,2,0] becomes shape [2,4,1] Type Description node $E[d_0,\dots,d_{n-1}]~(n \geq 0)$ An input tensor of any shape order AxisVector (empty default) The axes to eliminate through reduction (0 indexed). Output Type Description $E[d_{n-1},\dots,d_0)]\textit{ or }E[d_{order[0]},\dots,d_{order[n-1]}]$ The tensor $T$, where $T$ is the input tensor with the axes reordered via Numpy Transpose rules
size_t ngraph::builder::get_num_elements(const Shape &shape, const AxisSet &reduction_axes)
std::shared_ptr< Node > ngraph::builder::l2_norm(const std::shared_ptr< Node > &node, const AxisSet &reduction_axes)
Sum-based L2 Norm of a Tensor.
Calculates$\left(\sum_{i=1}^{N} x_i^2\right)^{0.5}$Where i traverses all of the axes provided in reduction_axesInputs Type Description node $E[d_1,\dots,d_n]~(n \geq 0)$ An input tensor of any shape reduction_axes AxesSet The axes to eliminate through reduction (0 indexed). Output Type Description $E[\textit{delete}(A,d_1,\dots,d_n)]$ The tensor $T$, where $T$ is the input tensor with the reduction_axes $A$ eliminated by reduction.
References ngraph::op::Constant::create.
std::shared_ptr< Node > ngraph::builder::mean(const std::shared_ptr< Node > &node, const AxisSet &reduction_axes)
Sum-based Mean of a Tensor.
Calculates$\sum_{i=1}^{N} \frac{x_i}{N}$Where i traverses all of the axes provided in reduction_axesInputs Type Description node $E[d_1,\dots,d_n]~(n \geq 0)$ An input tensor of any shape reduction_axes AxesSet The axes to eliminate through reduction (0 indexed). Output Type Description $E[\textit{delete}(A,d_1,\dots,d_n)]$ The tensor $T$, where $T$ is the input tensor with the reduction_axes $A$ eliminated by reduction.
References ngraph::op::Constant::create.
Referenced by variance.
std::shared_ptr< Node > ngraph::builder::std_dev(const std::shared_ptr< Node > &node, const AxisSet &reduction_axes, const bool bessel_correction=false)
Sum-based Standard Deviation of a Tensor.
If bessel_correct is true, calculates$\sqrt{\frac{\sum_{i=1}^{N}\left(x_i-\bar{x}\right)^2}{N-1}}$else, calculates$\sqrt{\frac{\sum_{i=1}^{N}\left(x_i-\bar{x}\right)^2}{N}}$Where i traverses all of the axes provided in reduction_axes and $\bar{x} = \sum_{i=1}^{N} \frac{x_i}{N}$Inputs Type Description node $E[d_1,\dots,d_n]~(n \geq 0)$ An input tensor of any shape reduction_axes AxesSet The axes to eliminate through reduction (0 indexed). bessel_correction bool (default = false) Enable Bessel's correction to std_dev for Small sample sizes Output Type Description $E[\textit{delete}(A,d_1,\dots,d_n)]$ The tensor $T$, where $T$ is the input tensor with the reduction_axes $A$ eliminated by reduction.
References variance, ngraph::op::Constant::create.
std::shared_ptr< Node > ngraph::builder::variance(const std::shared_ptr< Node > &node, const AxisSet &reduction_axes, const bool bessel_correction=false)
Sum-based Variance of a Tensor.
If bessel_correct is true, calculates$\frac{\sum_{i=1}^{N}\left(x_i-\bar{x}\right)^2}{N-1}$else, calculates$\frac{\sum_{i=1}^{N}\left(x_i-\bar{x}\right)^2}{N}$Where i traverses all of the axes provided in reduction_axes and $\bar{x} = \sum_{i=1}^{N} \frac{x_i}{N}$Inputs Type Description node $E[d_1,\dots,d_n]~(n \geq 0)$ An input tensor of any shape reduction_axes AxesSet The axes to eliminate through reduction (0 indexed). bessel_correction bool (default = false) Enable Bessel's correction to std_dev for Small sample sizes Output Type Description $E[\textit{delete}(A,d_1,\dots,d_n)]$ The tensor $T$, where $T$ is the input tensor with the reduction_axes $A$ eliminated by reduction.
References mean, ngraph::op::Constant::create.
Referenced by std_dev.