# Environment to build and unit-test private-ngraph-cpp

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
        build-essential cmake \
        clang-3.9 clang-format-3.9 \
        git \
        wget patch diffutils  

RUN apt-get clean autoclean && \
    apt-get autoremove -y

# Add chown_files script to avoid 
ADD contrib/docker/chown_files.sh /tmp/chown_files.sh

WORKDIR /root/ngraph-cpp-test
